name: weatherpro
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  http: ^1.1.2
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.2.1
  weather_icons: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4
  web: any
  share_plus: ^7.2.1
  hugeicons: ^0.0.7
  geocoding: ^4.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^3.0.3
  flutter_gen_runner: ^5.12.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - env.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.svg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.svg"